-- MySQL Script generated by MySQL Workbench
-- Mon Nov  5 11:13:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema carddb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carddb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carddb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `carddb` ;

-- -----------------------------------------------------
-- Table `carddb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carddb`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carddb`.`decks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carddb`.`decks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL,
  `description` VARCHAR(100) NOT NULL DEFAULT '',
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_idx` (`userId` ASC),
  CONSTRAINT `fk`
    FOREIGN KEY (`userId`)
    REFERENCES `carddb`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `carddb`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carddb`.`cards` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `deckId` INT(11) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `health` INT(11) NOT NULL,
  `damage` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `deckId`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `FK_Decks_Cards_idx` (`deckId` ASC),
  CONSTRAINT `FK_Decks_Cards`
    FOREIGN KEY (`deckId`)
    REFERENCES `carddb`.`decks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
